server:
  port: 8099
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8

# 数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: "jdbc:mysql://localhost:3306/flame?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    &allowPublicKeyRetrieval=true&useAffectedRows=true"

  jackson:
    default-property-inclusion: non_empty

#mybatis-plus 设置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    banner: false
    db-config:
      id-type: assign_id
  configuration:
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
