server:
  port: 8099
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8

# 数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: "jdbc:mysql://localhost:3306/flame?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai\
    &allowPublicKeyRetrieval=true&useAffectedRows=true"

#mybatis 设置
mybatis:
  mapper-locations: classpath*:mapper/*.xml